### ISSUE TITLE
[Question] - Can I use Boxy to build a Flutter version of Angular FlexLayouts 

### ISSUE THREAD

**Issue by dinbtechit** [pingbird/boxy#18]
Hi, I am pretty impressed by what you did with boxy! 

I am looking to build [Angular FlexLayout](https://github.com/angular/flex-layout/wiki/Declarative-API-Overview) for Flutter.

Responsive API - https://github.com/angular/flex-layout/wiki/Responsive-API

I am wondering if I can use Boxy for this. I'd appreciate it if you have any advice/ideas on how to accomplish the example shown below, or if you want to collaborate. I would be more than happy to be a part of it.

### Psuedo Code
```dart
FxLayout (
 layout: FxLayout.row,                               // by default  - displays as column
 md: FxLayout.column,                             // on medium screen - displays as column
 ltMd: FxLayout.column,                          // less than medium screens - displays as column
 mainAxisAlign: FxLayoutAlign.center,
 crossAxisAlign: FxLayoutAlign.center,
 gap: FxSize(size: 10, unit: FxUnit.dp /*default*/)
  children: [
    FxFlex (
       fill: true                                                   // very similar to Dominant
       order: 0,
       align: FxFlexAlign.start,
       child: Text('1st Child'),
     ),
    FxFlex (
       order: 1,                                                  // You can switch the order of the flex.
       align: FxFlexAlign.center,
       size: FxSize(size: 90, unit: FxUnit.percentage ),
       child: Text('2nd Child'),
     )
  ]
)
```
Cheers!

**Comment by PixelToast** [comment]
I looked into the many properties of FxLayout and couldn't find anything that couldn't be replicated with `Row`, `Column`, `Wrap`, `Padding`, `SizedBox`, etc. with the exception of breakpoints, where I recommend building your own with `LayoutBuilder` or use a package like https://pub.dev/packages/responsive_builder

If you have a running example in Angular or HTML that wouldn't be possible with the mentioned built-in widgets I'd be glad to help

**Comment by dinbtechit** [comment]
True! you could pretty much do everything except breakpoints with the existing widgets. 

I felt like the key features are: 
-  Breakpoints 
- Simple and consistent API simple.  (Just 2 widgets to remember the parent `FxLayout` and child `FxFlex`)
- Less code to write
- Feature Complete

With FxLayout we could also change the order of the children depending on the screen size, I dont think any of the inbuild widgets or 3rd party packages offer that. 

I tried responsive_builder and responsive_framework. They lack consistency and naming conventions are off.  I think it's a debatable topic on what is a good convention. I thought taking the concepts from a well-proven library would be a good idea.
