### ISSUE TITLE
Make `BoxyFlex` Implement `Flex`

### ISSUE THREAD

**Issue by caseycrogers** [pingbird/boxy#26]
Packages like [gap](https://pub.dev/packages/gap) and [flutter_gutter](https://pub.dev/packages/gap) use `Flex.direction`/`RenderFlex.direction` to determine if they are in a vertically or horizontally aligned layout.

`BoxyFlex` and `BoxyRenderFlex` should implement their Flutter counterparts so that these packages' widgets will work properly with `BoxyRow` and `BoxyColumn` out of the box(y).

Here's a related `Flutter/flutter` issue that if accepted would change how this should be implemented:
https://github.com/flutter/flutter/issues/133394

**Comment by pingbird** [comment]
This can't be done without breaking boxy when the framework changes Flex, also, walking the tree to check the runtime type of ancestors is probably a bad idea. I'll gladly implement a directionality interface if added to the framework, I think your best bet until then is a dynamic call at layout time:

```dart
var direction = 
try {
  direction = (parent as dynamic).direction as Axis;
} catch (e) {}
```
