### ISSUE TITLE
[Question] is there a simply way to change the Tree View so that it is horizontally oriented?

### ISSUE THREAD

**Issue by ForeverAngry** [pingbird/boxy#27]
I would like to make the tree view flow left to right, instead of, top to bottom - but I feel like I'm over complicating things with how im implementing it. Does anyone have any guidance on this ( or an example)? Any help is appreciated!

**Comment by pingbird** [comment]
I assume you are referring to the tree view example at https://boxy.wiki/custom-boxy/examples/tree-view/ 
Wrapping it in a [RotatedBox](https://api.flutter.dev/flutter/widgets/RotatedBox-class.html) would probably work, you would also want to wrap each child node in another RotatedBox.

**Comment by ForeverAngry** [comment]
Hi, thanks so much!  That worked great!
