### ISSUE TITLE
OverflowPadding hitTest

### ISSUE THREAD

**Issue by Maatteogekko** [pingbird/boxy#28]
The part of the child that is inside the negative insets does not receive hit tests. Can this be solved?

If not, then a warning in the documentation would be really useful to inform users about this limitation

**Comment by pingbird** [comment]
This is a feature of the framework unfortunately, children that are overpainted probably won't be hit tested. That reminds me, I was working on a widget that could work around this by hit testing the child directly from higher in the tree.

**Comment by Maatteogekko** [comment]
Yeah I feared that. Did you have in mind something like [this](https://pub.dev/packages/defer_pointer)?

**Comment by pingbird** [comment]
Yes, see https://pub.dev/documentation/boxy/latest/redirect_pointer/RedirectPointer-class.html

**Comment by MrLepage** [comment]
Hey @pingbird  @Maatteogekko ! 

I ran into the same issue. I think it could be solved directly in RenderOverflowPadding by overriding hitTest to skip the default size.contains bounds check.

Something like this should work:


```
@override
bool hitTest(BoxHitTestResult result, {required Offset position}) {
  _resolve();
  if (child case final child?) {
    return result.addWithPaintOffset(
      offset: Offset(_resolvedPadding!.left, _resolvedPadding!.top),
      position: position,
      hitTest: (result, transformed) => child.hitTest(result, position: transformed),
    );
  }
  return false;
}
```

The idea is to have the hit testing follow the same offset as the paint, so the overflow area would become tappable without needing RedirectPointer.

Do you see any edge case where this approach wouldn't work?

**Comment by Maatteogekko** [comment]
Hi @MrLepage !
I avoided this issue by refactoring my layouts.
I don't see any immediate problems with your code, but it remains an hack that runs against flutter's assumptions. It is bound to hit a bug sooner or later.
If this works for a specific layout, then good. But I wouldn't use it in a general solution.
