### ISSUE TITLE
Skip ignored children in `RenderObject.visitChildrenForSemantics`

### ISSUE THREAD

**Issue by Albert221** [pingbird/boxy#32]
As in the title, if we don't paint children by calling `BoxyChild.ignore()` inside a `BoxyDelegate`, we most likely don't want to include it in the semantics tree, so that the screen readers won't bother with the children we didn't want to paint.

**Comment by pingbird** [comment]
Should be fixed in 2.1.3, Thanks!

**Comment by Albert221** [comment]
That was a quick fix, thank you!
